version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'python3'
    working_dir: '/root/'
    tty: true
    volumes:
      - .:/root/
    ports:
      - 8888:8888
    environment:
      - JUPYTER_ENABLE_LAB=yes